import matplotlib.pyplot as plt
import io
import os
import tempfile
import uuid
from fpdf import FPDF
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from app.models.company import Company
from app.models.analysis import Analysis
from app.models.post import Post

async def generate_pdf(db: AsyncSession, company_id: int) -> str:
    """
    Generate a PDF report for a company including metrics and charts.
    Returns the path to the generated PDF file in the temp directory.
    """
    # 1. Fetch data
    result = await db.execute(select(Company).where(Company.id == company_id))
    company = result.scalars().first()
    if not company:
        raise ValueError("Company not found")

    result = await db.execute(
        select(Analysis)
        .where(Analysis.company_id == company_id)
        .order_by(Analysis.id.desc())
        .limit(1)
    )
    latest_analysis = result.scalars().first()

    # 2. Generate Chart using Matplotlib
    plt.figure(figsize=(8, 5))
    
    # Simple bar chart for engagement
    labels = ['Engagement Score']
    values = [latest_analysis.engagement_score if latest_analysis else 0]
    
    plt.bar(labels, values, color='#4A90E2')
    plt.ylim(0, max(values) * 1.2 if values[0] > 0 else 10)
    plt.title(f"Social Intelligence Metrics - {company.name}", fontsize=14)
    plt.ylabel("Score")
    
    # Save chart to a buffer
    img_buf = io.BytesIO()
    plt.savefig(img_buf, format='png', bbox_inches='tight')
    img_buf.seek(0)
    plt.close()

    # 3. Create PDF using FPDF2
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("helvetica", "B", 20)
    pdf.set_text_color(74, 144, 226) # Blue color
    pdf.cell(0, 15, "Social Intelligence Platform", ln=True, align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, f"Executive Report: {company.name}", ln=True, align="C")
    pdf.ln(10)
    
    # Content
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "Summary Metrics", ln=True)
    pdf.set_font("helvetica", "", 11)
    
    if latest_analysis:
        pdf.cell(0, 8, f"Average Engagement Score: {latest_analysis.engagement_score:.2f}", ln=True)
        pdf.cell(0, 8, f"Detected Hiring Signals: {latest_analysis.hiring_signals or 'None'}", ln=True)
    else:
        pdf.cell(0, 8, "No analysis data available for this company yet.", ln=True)
    
    pdf.ln(10)
    
    # Embed Chart
    # We need to save the buffer to a temporary file for FPDF to read it
    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp_img:
        tmp_img.write(img_buf.getvalue())
        tmp_img_path = tmp_img.name
    
    try:
        pdf.image(tmp_img_path, x=15, y=None, w=180)
    finally:
        if os.path.exists(tmp_img_path):
            os.unlink(tmp_img_path)
    
    pdf.ln(10)
    pdf.set_font("helvetica", "I", 10)
    pdf.cell(0, 10, "Generated by AI Social Intelligence Platform", align="C")

    # 4. Save PDF to temp directory
    report_filename = f"report_{company_id}_{uuid.uuid4().hex}.pdf"
    temp_dir = tempfile.gettempdir()
    report_path = os.path.join(temp_dir, report_filename)
    
    pdf.output(report_path)
    
    return report_path
