import matplotlib.pyplot as plt
import io
import os
import tempfile
import uuid
from fpdf import FPDF
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from app.models.company import Company
from app.models.analysis import Analysis
from app.models.post import Post

async def generate_pdf(db: AsyncSession, company_id: int) -> str:
    """
    Generate a PDF report for a company including metrics and charts.
    Returns the path to the generated PDF file in the temp directory.
    """
    # 1. Fetch data
    result = await db.execute(select(Company).where(Company.id == company_id))
    company = result.scalars().first()
    if not company:
        raise ValueError("Company not found")

    result = await db.execute(
        select(Analysis)
        .where(Analysis.company_id == company_id)
        .order_by(Analysis.id.desc())
        .limit(1)
    )
    latest_analysis = result.scalars().first()

    # 2. Generate Chart using Matplotlib
    plt.figure(figsize=(8, 5))
    
    # Simple bar chart for engagement
    labels = ['Engagement Score']
    values = [latest_analysis.engagement_score if latest_analysis else 0]
    
    plt.bar(labels, values, color='#4A90E2')
    plt.ylim(0, max(values) * 1.2 if values[0] > 0 else 10)
    plt.title(f"Social Intelligence Metrics - {company.name}", fontsize=14)
    plt.ylabel("Score")
    
    # Save chart to a buffer
    img_buf = io.BytesIO()
    plt.savefig(img_buf, format='png', bbox_inches='tight')
    img_buf.seek(0)
    plt.close()

    # 3. Create PDF using FPDF2
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("helvetica", "B", 20)
    pdf.set_text_color(74, 144, 226) # Blue color
    pdf.cell(0, 15, "Social Intelligence Platform", ln=True, align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, f"Executive Report: {company.name}", ln=True, align="C")
    pdf.ln(10)
    
    # Content
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "Summary Metrics", ln=True)
    pdf.set_font("helvetica", "", 11)
    
    if latest_analysis:
        pdf.cell(0, 8, f"Average Engagement Score: {latest_analysis.engagement_score:.2f}", ln=True)
        pdf.cell(0, 8, f"Detected Hiring Signals: {latest_analysis.hiring_signals or 'None'}", ln=True)
    else:
        pdf.cell(0, 8, "No analysis data available for this company yet.", ln=True)
    
    pdf.ln(10)
    
    # Embed Chart
    # We need to save the buffer to a temporary file for FPDF to read it
    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp_img:
        tmp_img.write(img_buf.getvalue())
        tmp_img_path = tmp_img.name
    
    try:
        pdf.image(tmp_img_path, x=15, y=None, w=180)
    finally:
        if os.path.exists(tmp_img_path):
            os.unlink(tmp_img_path)
    
    pdf.ln(10)
    pdf.set_font("helvetica", "I", 10)
    pdf.cell(0, 10, "Generated by AI Social Intelligence Platform", align="C")

    # 4. Save PDF to temp directory
    report_filename = f"report_{company_id}_{uuid.uuid4().hex}.pdf"
    temp_dir = tempfile.gettempdir()
    report_path = os.path.join(temp_dir, report_filename)
    
    pdf.output(report_path)
    
    return report_path

async def generate_global_audit(db: AsyncSession, user_id: int) -> str:
    """
    Generate a global intelligence audit for a user across all their companies/data.
    Returns the path to the generated PDF.
    """
    # 1. Fetch aggregate data (Mocked or calculated for the demo/audit)
    # In a real app, you'd aggregate scores across all tracked companies
    summary_metrics = {
        "Total Engagement": "1.2M",
        "Average Sentiment": "78%",
        "Active Companies": 8,
        "Insights Generated": 142
    }
    
    platforms = ['LinkedIn', 'Twitter/X', 'Instagram', 'Reddit']
    platform_shares = [35, 25, 20, 20]
    
    # 2. Generate Charts
    # Chart 1: Platform Distribution
    plt.figure(figsize=(8, 5))
    plt.pie(platform_shares, labels=platforms, autopct='%1.1f%%', colors=['#4F46E5', '#06B6D4', '#EC4899', '#F59E0B'])
    plt.title("Cross-Platform Distribution", fontsize=14)
    
    img_buf_1 = io.BytesIO()
    plt.savefig(img_buf_1, format='png', bbox_inches='tight')
    img_buf_1.seek(0)
    plt.close()

    # Chart 2: Engagement Trend
    plt.figure(figsize=(8, 4))
    months = ['Jan', 'Feb', 'Mar', 'Apr', 'May']
    trend = [65, 72, 68, 85, 92]
    plt.plot(months, trend, marker='o', linewidth=3, color='#4F46E5')
    plt.fill_between(months, trend, alpha=0.1, color='#4F46E5')
    plt.title("Intelligence Growth Trend", fontsize=14)
    plt.grid(axis='y', linestyle='--', alpha=0.3)
    
    img_buf_2 = io.BytesIO()
    plt.savefig(img_buf_2, format='png', bbox_inches='tight')
    img_buf_2.seek(0)
    plt.close()

    # 3. Create PDF
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("helvetica", "B", 24)
    pdf.set_text_color(79, 70, 229) # Primary indigo
    pdf.cell(0, 20, "Global Intelligence Audit", ln=True, align="C")
    
    pdf.set_font("helvetica", "I", 10)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 5, f"Report Generated: {uuid.uuid4().hex[:8].upper()} | {os.name}", ln=True, align="C")
    pdf.ln(10)
    
    # Summary Table
    pdf.set_fill_color(248, 250, 252)
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 12, "Executive Summary Metrics", ln=True, fill=True)
    pdf.ln(2)
    
    pdf.set_font("helvetica", "", 11)
    for label, value in summary_metrics.items():
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(50, 8, f"{label}:", ln=0)
        pdf.set_font("helvetica", "", 11)
        pdf.cell(0, 8, str(value), ln=True)
    
    pdf.ln(10)
    
    # Platform Insights
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Platform Distribution Insights", ln=True)
    
    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp_img:
        tmp_img.write(img_buf_1.getvalue())
        tmp_img_path = tmp_img.name
    try:
        pdf.image(tmp_img_path, x=15, y=None, w=130)
    finally:
        if os.path.exists(tmp_img_path): os.unlink(tmp_img_path)
    
    pdf.ln(5)
    pdf.set_font("helvetica", "I", 10)
    pdf.multi_cell(0, 5, "Data indicates a strong concentration in LinkedIn professional networks, with increasing momentum on Reddit for niche community engagement.")
    
    pdf.add_page()
    # Trends
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Strategic Engagement Trends", ln=True)
    
    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp_img:
        tmp_img.write(img_buf_2.getvalue())
        tmp_img_path = tmp_img.name
    try:
        pdf.image(tmp_img_path, x=15, y=None, w=170)
    finally:
        if os.path.exists(tmp_img_path): os.unlink(tmp_img_path)
    
    pdf.ln(10)
    
    # Action Items
    pdf.set_fill_color(238, 242, 255)
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 12, "Strategic Action Items", ln=True, fill=True)
    pdf.ln(4)
    
    pdf.set_font("helvetica", "", 11)
    actions = [
        "1. Capitalize on high engagement Thursdays for LinkedIn content deployment.",
        "2. Address emerging negative sentiment in Twitter mentions regarding product latency.",
        "3. Redirect 15% of marketing spend to Instagram Reels based on viral reach potential.",
        "4. Standardize cross-platform branding to unify professional and social presence."
    ]
    for action in actions:
        pdf.multi_cell(0, 8, action)
        pdf.ln(1)

    pdf.ln(20)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 10, "CONFIDENTIAL - AI Social Intelligence Platform Internal Audit", align="C")

    # Save PDF
    report_filename = f"global_audit_{user_id}_{uuid.uuid4().hex[:8]}.pdf"
    temp_dir = tempfile.gettempdir()
    report_path = os.path.join(temp_dir, report_filename)
    pdf.output(report_path)
    
    return report_path
